INSERT INTO DEV_DB.DEV_SCHEMA.DEMO_TABLE1 (ID, NAME, CREATED_AT)
VALUES (1, 'Alice', CURRENT_TIMESTAMP);

INSERT INTO DEV_DB.DEV_SCHEMA.DEMO_TABLE1 (ID, NAME, CREATED_AT)
VALUES (2, 'Bob', CURRENT_TIMESTAMP);

INSERT INTO DEV_DB.DEV_SCHEMA.DEMO_TABLE1 (ID, NAME, CREATED_AT)
VALUES (3, 'Charlie', CURRENT_TIMESTAMP);
